FROM alpine:latest

# Install the streaming unzip scripts from current directory to /usr/local/bin
COPY unzip.sh /usr/local/bin
COPY write-item.sh /usr/local/bin

# Install the packages needed by the bsdtar unzip scripts.
# Note that we're installing the full tar package as busybox tar does not
# support the --to-command option necessary for the correct functioning of
# the unzip script. Note too that aws-cli is not yet released to a stable
# alpine version, it is only the in edge/testing repository, so need to install
# in a more manual way - found ideas here https://github.com/mesosphere/aws-cli
RUN apk update && apk upgrade && \
    apk add bash curl tar libarchive-tools jq \
    python py-pip groff && \
    pip install --upgrade awscli==1.14.5 s3cmd==2.0.1 python-magic && \
    apk -v --purge del py-pip && \
    rm -rf /var/cache/apk/*

CMD ["/usr/local/bin/unzip.sh"]

#-------------------------------------------------------------------------------
# Build the image
# docker build -t bsdtar-unzip -f Dockerfile-standalone .
#
# This Dockerfile builds an unzip image standalone without the hotwrap
# entrypoint so the entrypoint becomes the unzip executable itself. The
# docker-unzip.sh executable is the best way to run this as it requires
# AWS key environment variables passed to the container.
