#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Create a really simple Docker container registry for use by
# a Kubernetes cluster such as kind.

# N.B. this is just a toy registry for experiments to avoid having to use
# the public Docker Hub. Clearly for production a more production ready
# private repository is required.

# registry URL is: $(hostname -I | awk '{print $1}'):5000

# Test it 
# docker pull ubuntu
# docker tag ubuntu localhost:5000/ubuntu
# docker push localhost:5000/ubuntu

# or

# docker pull ubuntu
# docker tag ubuntu $(hostname -I | awk '{print $1}'):5000/ubuntu
# docker push $(hostname -I | awk '{print $1}'):5000/ubuntu

docker run --rm -d \
    --name registry \
    -p 5000:5000 \
    registry:2

# http://localhost:5000/v2/_catalog
# Registry browser UI
# https://hub.docker.com/r/klausmeyer/docker-registry-browser/
#docker run --rm -d \
#    --name registry-browser \
#    -p 5001:8080 \
#    -e DOCKER_REGISTRY_URL=http://localhost:5000 \
#    klausmeyer/docker-registry-browser
    
